"""MEND algorithm: pure tensor functions for proximal velocity matching (cap, propose, verify, regress).

Everything here runs on CPU and is covered by the tests in ``tests/``.

Conventions:
  * rectified flow z_t = (1 - t) x0 + t eps, velocity v = eps - x0, x0-prediction xhat = z - t v;
  * t is the scheduler sigma and the grid runs 1 = t_0 > t_1 > ... > t_N = 0;
  * ||u||^2 means the elementwise mean of u^2 per sample (not the sum).
"""

from .common import (  # noqa: F401
    LORA_TARGET_MODULES,
    TensorOrList,
    VelocityFn,
    _bshape,
    rms,
    sigma_to_index,
    sq_mean,
)
from .diagnostics import (  # noqa: F401
    PROBE_KEYS,
    hf_energy,
    probe_stats,
    realization_ratio,
)
from .proposals import (  # noqa: F401
    anchored_proposals,
    clip_hint,
    explicit_proposals,
    restart_corrected,
    reward_hint,
)
from .repair import (  # noqa: F401
    contrastive_repair,
    fixed_rms_repair,
    lowpass_repair,
    spot_mask_repair,
)
from .rollout import (  # noqa: F401
    branch_states,
    cfg_direction,
    guided_velocity,
    invert_euler,
    restart_denoise,
    restart_history,
    rollout_dpm2,
    rollout_euler,
)
from .targets import (  # noqa: F401
    FRESH_TARGET_MODES,
    PATH_HIGH_MODES,
    PATH_SHAPES,
    TRAIN_STATE_MODES,
    displaced_path,
    fm_pair_target,
    fresh_state,
    loss_weights,
    nft_loss,
    path_allowed_indices,
    path_loss_terms,
    path_state_target,
    sample_fresh_t,
    sample_train_indices,
    single_state_x0_target,
    train_state_indices,
    train_state_indices_split,
    velocity_mse,
    x0_loss,
)
from .tau import (  # noqa: F401
    TauController,
    lr_at,
    step_growth_scale,
)
from .verdict import (  # noqa: F401
    _gmm_full,
    capped,
    cluster_cap,
    confirm_verdict,
    estimate_noise_sigma,
    gain_scale,
    gmm_bic_labels,
    group_cap,
    group_std,
    hint_perp_sq,
    pareto_feasible,
    proximal_verdict,
    relative_cap,
    update_kappa_glob,
)

__all__ = [
    "sq_mean",
    "rms",
    "sigma_to_index",
    "TensorOrList",
    "VelocityFn",
    "LORA_TARGET_MODULES",
    "rollout_dpm2",
    "rollout_euler",
    "guided_velocity",
    "cfg_direction",
    "restart_history",
    "restart_denoise",
    "invert_euler",
    "branch_states",
    "reward_hint",
    "clip_hint",
    "explicit_proposals",
    "anchored_proposals",
    "restart_corrected",
    "group_cap",
    "group_std",
    "relative_cap",
    "gain_scale",
    "gmm_bic_labels",
    "cluster_cap",
    "update_kappa_glob",
    "capped",
    "pareto_feasible",
    "proximal_verdict",
    "hint_perp_sq",
    "estimate_noise_sigma",
    "confirm_verdict",
    "TauController",
    "step_growth_scale",
    "lr_at",
    "lowpass_repair",
    "spot_mask_repair",
    "fixed_rms_repair",
    "contrastive_repair",
    "displaced_path",
    "single_state_x0_target",
    "sample_train_indices",
    "TRAIN_STATE_MODES",
    "train_state_indices",
    "PATH_SHAPES",
    "PATH_HIGH_MODES",
    "path_allowed_indices",
    "train_state_indices_split",
    "path_state_target",
    "FRESH_TARGET_MODES",
    "sample_fresh_t",
    "fresh_state",
    "x0_loss",
    "nft_loss",
    "fm_pair_target",
    "velocity_mse",
    "path_loss_terms",
    "loss_weights",
    "realization_ratio",
    "PROBE_KEYS",
    "probe_stats",
    "hf_energy",
]
